swagger: "2.0"
info:
  description: RESTFUL API wrapper for OpenEMPI 
  version: "1.0.0"
  title: Personal Identifier Information (PII) API 
consumes:
  - application/json
produces:
  - application/json
basePath: /pii
tags:
- name: "Person"
  description: "Person entity"
schemes:
- "https"
- "http"

paths:
  /findPersonById:
    post:
      operationId: controllers.person.findPersonById
      tags:
        - Person 
      summary: Find person by id
      description: Find person by id
      parameters:
        - name: item 
          in: body
          description: Person to queue 
          required: True
          schema:
            $ref: "#/definitions/PersonId"
      responses:
        200:
          description: OK

  /findPersonByAttributes:
    post:
      operationId: controllers.person.findPersonByAttributes
      tags:
        - Person 
      summary: Find person by attribute search
      description: Find person by attribute search
      parameters:
        - name: item 
          in: body
          description: Person to search by attribute 
          required: True
          schema:
            $ref: "#/definitions/PersonId"
      responses:
        200:
          description: OK

  /addPerson:
    put:
      operationId: controllers.person.addPerson
      tags:
        - Person 
      summary: Add person
      description: Add new person
      parameters:
        - name: item 
          in: body
          description: Add new perosn to queue 
          required: True
          schema:
            $ref: "#/definitions/PersonId"
      responses:
        200:
          description: OK

definitions:
  PersonId:
    type: "object"
    properties:
      id:
        type: "string"
        description: "person id"