swagger: "2.0"
info:
  description: RESTFUL API with abstracted RabbitMQ 
  version: "1.0.0"
  title: RESTHooks
consumes:
  - application/json
produces:
  - application/json

basePath: /amqp

# Paths supported by the server application
paths:

  /order:
    post:
      operationId: order.create
      tags:
        - OpenCart to Dispergo and Idiah 
      summary: Queue an order  
      description: Create a new order queue 
      parameters:
        - name: item 
          in: body
          description: Order to queue 
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: name of item to be queued 
              quantity:
                type: string
                description: quantitye of item to be queued 
      responses:
        201:
          description: Successfully created order queue 